/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewCoachRouteImport } from './routes/interview-coach'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityTypeIdRouteImport } from './routes/opportunity.$type.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewCoachRoute = InterviewCoachRouteImport.update({
  id: '/interview-coach',
  path: '/interview-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityTypeIdRoute = OpportunityTypeIdRouteImport.update({
  id: '/opportunity/$type/$id',
  path: '/opportunity/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/opportunity/$type/$id': typeof OpportunityTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/opportunity/$type/$id': typeof OpportunityTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/cover-letter': typeof CoverLetterRoute
  '/interview-coach': typeof InterviewCoachRoute
  '/jobs': typeof JobsRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/opportunity/$type/$id': typeof OpportunityTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/cover-letter'
    | '/interview-coach'
    | '/jobs'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/roadmap'
    | '/saved'
    | '/settings'
    | '/opportunity/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/cover-letter'
    | '/interview-coach'
    | '/jobs'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/roadmap'
    | '/saved'
    | '/settings'
    | '/opportunity/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/assistant'
    | '/auth'
    | '/cover-letter'
    | '/interview-coach'
    | '/jobs'
    | '/notifications'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/roadmap'
    | '/saved'
    | '/settings'
    | '/opportunity/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CoverLetterRoute: typeof CoverLetterRoute
  InterviewCoachRoute: typeof InterviewCoachRoute
  JobsRoute: typeof JobsRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  OpportunityTypeIdRoute: typeof OpportunityTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-coach': {
      id: '/interview-coach'
      path: '/interview-coach'
      fullPath: '/interview-coach'
      preLoaderRoute: typeof InterviewCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$type/$id': {
      id: '/opportunity/$type/$id'
      path: '/opportunity/$type/$id'
      fullPath: '/opportunity/$type/$id'
      preLoaderRoute: typeof OpportunityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CoverLetterRoute: CoverLetterRoute,
  InterviewCoachRoute: InterviewCoachRoute,
  JobsRoute: JobsRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  OpportunityTypeIdRoute: OpportunityTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
